version: "3.8"

services:
  postgres-db:
    container_name: blogsDB-container
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: alfredo
      POSTGRES_DB: blogs
      POSTGRES_PASSWORD: ye2010olbap
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432